# $: docker-compose up --build
version: "3"
services:
  mongodb:
    image: mongo:latest
  seed_mongo:
    build:
      context: ./seeder
      dockerfile: Dockerfile
    depends_on:
      - mongodb
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    image: app
    depends_on:
      - mongodb
